projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "https://texty-prod-server.herokuapp.com/"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
