projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "https://eu1.prisma.sh/anker-bach-ryhl/texty-app/prod"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
